version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aa_sharing
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d aa_sharing"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/aa_sharing?sslmode=disable
      JWT_SECRET: your-jwt-secret-key-change-this-in-production
      PORT: 8080
      GIN_MODE: debug
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: go run cmd/main.go

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080

volumes:
  postgres_data:
  redis_data: